const withVar = (name) => `var(${name})`

const preset = {
  theme: {
    extend: {
      colors: {
        c: {
          brand: withVar("--w-c-brand"),
          "brand-80": withVar("--w-c-brand-80"),
          "brand-60": withVar("--w-c-brand-60"),
          "brand-40": withVar("--w-c-brand-40"),
          "brand-20": withVar("--w-c-brand-20"),
          "brand-10": withVar("--w-c-brand-10"),
          content: withVar("--w-c-content"),
          subtitle: withVar("--w-c-subtitle"),
          attachment: withVar("--w-c-attachment"),
          card: withVar("--w-c-card"),
          global: withVar("--w-c-global"),
          dividing: withVar("--w-c-dividing"),
          contrast: withVar("--w-c-contrast"),
          link: withVar("--w-c-link"),
          focus: withVar("--w-c-focus"),
          alart: withVar("--w-c-alart"),
        },
        btn: {
          "orange-a": withVar("--w-btn-orange-a"),
          "orange-b": withVar("--w-btn-orange-b"),
          "orange-pressed-a": withVar("--w-btn-orange-pressed-a"),
          "orange-pressed-b": withVar("--w-btn-orange-pressed-b"),
          "orange-fil": withVar("--w-btn-orange-fil"),
          gray: withVar("--w-btn-gray"),
          "gray-pressed": withVar("--w-btn-gray-pressed"),
          "gray-disabled": withVar("--w-btn-gray-disabled"),
          "gray-stroke": withVar("--w-btn-gray-stroke"),
          link: withVar("--w-btn-link"),
          "link-pressed": withVar("--w-btn-link-pressed"),
          "link-stroke": withVar("--w-btn-link-stroke"),
        },
        black: {
          80: withVar("--w-black-80"),
          60: withVar("--w-black-60"),
          40: withVar("--w-black-40"),
          20: withVar("--w-black-20"),
          10: withVar("--w-black-10"),
        },
        white: {
          80: withVar("--w-white-80"),
          60: withVar("--w-white-60"),
          40: withVar("--w-white-40"),
          20: withVar("--w-white-20"),
          10: withVar("--w-white-10"),
        },
      },
      borderRadius: {
        none: "0px",
        xsmall: "2px",
        small: "4px",
        medium: "6px",
        large: "8px",
        xlarge: "10px",
        xxlarge: "12px",
        xxxlarge: "16px",
        full: "999px",
      },
      spacing: {
        none: "0px",
        "2xs": "2px",
        xs: "4px",
        sm: "6px",
        "md-compact": "8px",
        "md-tight": "10px",
        md: "12px",
        "md-relaxed": "14px",
        lg: "16px",
        xl: "24px",
        "2xl": "32px",
        "container-padding": withVar("--spacing-container-padding"),
      },
      fontFamily: {
        sans: [
          "-apple-system",
          "BlinkMacSystemFont",
          "PingFang SC",
          "HarmonyOS Sans SC",
          "Microsoft YaHei",
          "Roboto",
          "Helvetica",
          "Arial",
          "sans-serif",
        ],
      },
      boxShadow: {
        hairline: "0 0.5px 0 0 var(--w-c-dividing)",
        "hairline-top": "0 -0.5px 0 0 var(--w-c-dividing)",
        xs: "0 1px 2px 0 #0000000A, 0 0 4px 0 #00000005",
        sm: "0 1px 3px 0 #0000000F, 0 2px 8px 0 #0000000A",
        md: "0 2px 4px 0 #00000014, 0 4px 16px 0 #0000001A",
        lg: "0 4px 8px 0 #0000000F, 0 8px 24px 0 #0000000F, 0 0 40px 0 #00000008",
        xl: "0 8px 16px 0 #00000014, 0 16px 40px 0 #0000000F, 0 0 64px 0 #0000000A",
        "orange-glow": "0 0 12px 0 #FF820026, 0 0 24px 0 #FF820014",
        card: "0 1px 3px 0 #0000000F, 0 2px 8px 0 #0000000A",
        modal:
          "0 8px 16px 0 #00000014, 0 16px 40px 0 #0000000F, 0 0 64px 0 #0000000A",
      },
      screens: {
        mobile: { max: "599px" },
        foldable: { min: "600px", max: "904px" },
        pad: "905px",
      },
    },
  },
}

export default preset
